spring:
  datasource:
    url: jdbc:h2:mem:chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

springdoc:
  swagger-ui:
    path: swagger.html
  version: v1
  paths-to-match: /api/v1/**,/auth/**

logging:
  level:
    org.hibernate.SQL: debug
    reactor.netty.http.client: DEBUG
    chat.api.mapper: debug

mybatis:
  type-aliases-package: chat.api

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400