spring:
  datasource:
    url: jdbc:h2:mem:chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    reactor.netty.http.client: DEBUG
    chat.api.mapper: debug

mybatis:
  type-aliases-package: chat.api.model
