spring:
  datasource:
    url: jdbc:h2:mem:chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: localhost
    port: 6379
  profiles:
    include: aws

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: dong-chat
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      fetch-min-size: 1MB
      max-poll-records: 1000
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      message-topic: message
      read-topic: read
      enter-topic: enter

  data:
    mongodb:
      host: localhost
      port: 27017
      database: dong_chat

springdoc:
  swagger-ui:
    path: swagger.html
  paths-to-match: /api/**,/auth/**

logging:
  level:
    org.hibernate.SQL: debug
    reactor.netty.http.client: DEBUG
    chat.api.mapper: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mybatis:
  type-aliases-package: chat.api

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

cloud:
  aws:
    s3:
      bucket: dong-chat-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false